### ISSUE TITLE
Add example api call from angular to express in documentation or code

### ISSUE THREAD

**Issue by sbehun** [wlepinski/generator-meanstack#11]
Beginner angular user, total noob MEAN user here.  Maybe I should be posting this to stack, but, I'd greatly appreciate an example either in the documentation or maybe from the angular main controller on how to call an express js route and retrieve some json.  I understand how to use the services layer in angular, I think my problem is with express.

I've tried adding a route and currently have the following code returning 404 - Cannot GET /api/test
/routes/test.js

``` js
module.exports = function (app) {
    app.get('/api/test', function (req, res, next) {
        res.send('Hello World');
    });
};
```

Any ideas?  Thanks.

**Comment by wlepinski** [comment]
You need to create the specified route on server-side. Look at the app.js and routes folder.
