### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by dirkk0** [wlepinski/generator-meanstack#12]
Hi,

I am not too familiar with yo yet, and it is very much possible that I made a very obvious mistake.

I updated yo, installed the meanstack generator and have no errors on the command line:

```
Running "server" task

Running "clean:server" (clean) task

Running "concurrent:server" (concurrent) task

    Running "coffee:dist" (coffee) task

    Done, without errors.

Running "express:livereload" (express) task

Running "open:server" (open) task

Running "watch" task
Waiting...
```

The server seems to be running but the browser can't connect. `lsof -i :3000` is blank, so no server is running on port 3000.

A standard AngularJS app does work, so yo in general seems to be ok.

Any ideas what the problem might by? I am on MacOSX, node is v0.10.12 and yo is v1.0.4.

Thanks,
  Dirk

**Comment by frankbolviken** [comment]
I have the same issue. Please update if you found the solution :)

**Comment by dirkk0** [comment]
I know why it is, but not what the workaround is.

In line 271 of the Gruntfile.js it says:

```
if (target === 'dist') {
  return grunt.task.run(['build', 'open', 'express:dist', 'express-keepalive']);
}
```

Since you cannot set a target with `grunt server` (or can you?) the express server won't get started.

Once you comment this out, it works - but the live reload does not.

So I am missing something here - this line must be in there for a reason.

**Comment by sgentile** [comment]
You set the target by setting the node_env value

**Comment by dirkk0** [comment]
Ah, thanks!

That would be `NODE_ENV=dist grunt server` then?

I did that and inserted a console.log(target) and this gives me still an 'undefined' ...?

**Comment by sgentile** [comment]
http://stackoverflow.com/questions/18345179/how-to-run-grunt-server-in-dist-directory-instead-of-app-directory

if (process.env.NODE_ENV == 'production') {
    app.use(express.static('/dist'));
}else{
    app.use(express.static('/app'));  
}

**Comment by dirkk0** [comment]
@sgentile first of all - thanks a bunch for your help!!

The script above uses a different folder for the distribution and thus is useful per se.

What I don't understand is why grunt wouldn't start the express server at all in the development environment - which was the problem in the first place?

I was expecting to be able to start 'grunt server' (in both production and development), point my browser to some.ip:3000 and be able to change client and server sided code with live reload.

Or is that simply not possible with yeoman/grunt?

Again, thanks!

**Comment by sgentile** [comment]
livereload with grunt is a client side "plugin" - that would be useful when changing the client.  You would also need something for the server side, ie. https://github.com/josh/node-livereload

grunt 'x'  - 'x' can be any task you define, you can run grunt build and it will just run the build.  You can define exactly what you want run - in this case 'server' is just a collection of different tasks run together.

yeoman is mostly just a scaffolding tool, which so happens to scaffold out default type grunt files based on your project.

But again, I think all you are missing in what you want is to start up the node using a server watch piece.  What I would look for is a grunt task that does this for you - maybe like this 'rerun' example : http://stackoverflow.com/questions/19457002/grunt-contrib-watch-fire-livereload-event-after-grunt-nodemon-has-restarted

Hope that helps!

**Comment by wlepinski** [comment]
@dirkk0. Can you please confirm if you're using the 0.1.0 version of generator-meanstack?

**Comment by dirkk0** [comment]
@wlepinski yes, it is.
@sgentile Thank you!  I understood that Yeoman deals with the client side and I need an additional tool in grunt to watch updates of the server side. I was under the impression that this project had this.

In the meantime I checked out the [Klei](https://github.com/klei-dev/generator-klei) Generator and from my first tests it does exactly what I expected it to do.

**Comment by luisrudge** [comment]
I can confirm that this is indeed not working. I have the latest version and have the same problem.

**Comment by eddiemoore** [comment]
I can confirm this issue.
Running the 0.1.0 generator
Yeoman version 1.0.6
npm version 1.3.11
node v 0.10.21

**Comment by wlepinski** [comment]
@eddiemoore The only difference between my env and yours is the npm version (mine is 1.3.14) but I think this should not make any difference at all. 

I'll look if I can at least reproduce the issue on my environment and let you guys know.

**Comment by wlepinski** [comment]
Hi all, this is what I get after running these commands:

``` bash
yo meanstack
grunt server
```

The output after <code>grunt server</code> is the following:

``` bash
Running "server" task

Running "clean:server" (clean) task

Running "concurrent:server" (concurrent) task

    Running "coffee:dist" (coffee) task

    Done, without errors.

Running "express:livereload" (express) task

Running "open:server" (open) task

Running "watch" task
Waiting...OK

Running "express-server:livereload:/var/folders/90/6dg579k92zv8pcsp6_ggnyg540snwm/T/express1131118-69035-2kj4z1/livereload.server" (express-server) task
Web server started on port:3000, no hostname specified [pid: 69039]

Running "express-keepalive" task
```

One problem I noticed is that the grunt-open plugin ran earlier than it should run. So you get a browser page with a error message telling 'Oops! Google Chrome could not connect to localhost:3000' for example. But if you refresh the page after 3 seconds the server is up and running as expected.

For you guys, try running the project with the environment variable DEBUG with the value \* and paste the results here so that I can check what is going on, ok?

``` bash
export DEBUG=*
```

**Comment by wlepinski** [comment]
Another point.

If you want to serve the files using the dist folder you need to use the following command:

``` base
grunt server:dist
```

**Comment by eddiemoore** [comment]
I'm just getting:

```
Running "server" task

Running "clean:server" (clean) task

Running "concurrent:server" (concurrent) task

    Running "coffee:dist" (coffee) task

    Done, without errors.

Running "express:livereload" (express) task

Running "open:server" (open) task

Running "watch" task
Waiting...  tinylr:server Configuring HTTP server +0ms
```

And even if I refresh the page it doesn't load up.

**Comment by wlepinski** [comment]
@eddiemoore, Looking at the output looks like you don't reach the express-server tasks, which is the task that brings up the server on port 3000. Something is happening during the tinylr:server that your output is not showing. Try setting the DEBUG environment variable to \* and send the log again.

**Comment by eddiemoore** [comment]
@wlepinski That is what I get with the DEBUG environment variable set to *.

**Comment by thameera** [comment]
I can confirm the issue exists. `grunt server` nor `grunt server:dist` seems to work. Crunchbang Linux, Node v0.10.24, generator-meanstack v0.1.0. 
Would like to provide any logs/info if necessary.

**Comment by sesteva** [comment]
This seems to be a problem with grunt-express. Switching serverreload to false is a quick fix to make you app work in your development env. Reload over the app folder keeps working.

The serverreload starts a forever running server. The server is running in the same process as grunt, and will only live as long as the grunt process is running.

Setting serverreload to false should require us to add the keepalive task to avoid our server from stopping.

But on the generator our 'server' task already has a watch task at the end. This keeps grunt running and the express server alive.

I could not figure out how to fix it yet so the reload works for the server side scripts.

**Comment by wlepinski** [comment]
https://github.com/blai/grunt-express#express-keepalive

**Comment by xapou** [comment]
Same issue for me. 
Setting `serverreload: false` does the trick for the app.
Any progress on this issue ?
