### ISSUE TITLE
jshint issue on app.js

### ISSUE THREAD

**Issue by mcneela86** [wlepinski/generator-meanstack#24]
When I run 'yo meanstack' and immediately run 'grunt' (without editing anything) I get the following errors/warnings:

Running "jshint:all" (jshint) task
Linting app/scripts/app.js ...ERROR
[L9:C17] W015: Expected 'templateUrl' to have an indentation at 11 instead at 17.
                templateUrl: 'views/main.html',
Linting app/scripts/app.js ...ERROR
[L10:C17] W015: Expected 'controller' to have an indentation at 11 instead at 17.
                controller: 'MainCtrl'
Linting app/scripts/app.js ...ERROR
[L11:C13] W015: Expected '}' to have an indentation at 9 instead at 13.
            })
Linting app/scripts/app.js ...ERROR
[L13:C17] W015: Expected 'redirectTo' to have an indentation at 11 instead at 17.
                redirectTo: '/'
Linting app/scripts/app.js ...ERROR
[L14:C13] W015: Expected '}' to have an indentation at 9 instead at 13.
            });
Linting app/scripts/app.js ...ERROR
[L15:C5] W015: Expected '}' to have an indentation at 7 instead at 5.
    });
Linting app/scripts/app.js ...ERROR
[L17:C1] W015: Expected '}' to have an indentation at 3 instead at 1.
}.call(this));
Linting app/scripts/app.js ...ERROR
[L17:C8] W040: Possible strict violation.
}.call(this));

**Comment by simonwalsh** [comment]
+1

**Comment by wlepinski** [comment]
I'll look into this.

**Comment by fvenegasp** [comment]
I have the same problem

**Comment by aaroncollyer** [comment]
I have the same issue. Let us know if you need any more information.

**Comment by ghost** [comment]
Still a problem in the generated scaffold.
The tabs are resolved easy enough (just move the indents to the locations jshint expects them.
The strict error on L17 is a valid error; using "this" in this case is verbose anyway and can just be removed.

// will issue a pull request when I get a chance
'use strict';
(function(){
.....
}.call());

**Comment by ghost** [comment]
Submitted a pull request with the errors resolved - minor edit. Unfortunately, it did not attach to this issue... You can find the pull request [here](https://github.com/wlepinski/generator-meanstack/pull/25)
