### ISSUE TITLE
Model folder?

### ISSUE THREAD

**Issue by arch1t3ct** [wlepinski/generator-meanstack#3]
Why did you remove it? Where should model files go?

**Comment by wlepinski** [comment]
Hey @arch1t3ct. You can still put your models on the model folder. I just removed it from the current source-code because it will appear again on the next release of the generator. ;)

**Comment by fyockm** [comment]
@wlepinski When might we expect that next release of the generator with models reinstated?
I've been working on a project based on [mean.io](http://www.mean.io/) and would love to switch to a generator-angular based approach, but I'm not sure if this is quite ready yet.

**Comment by wlepinski** [comment]
Hey @fyockm. I don't have a specific date for a release on this generator. I'm planning to release this year but I'm very very busy on another project. I took a look on your project, but would be nice if you could explain what exactly what you project does so we can work on a release that fill both projects. What do you think?
