### ISSUE TITLE
TypeError: Cannot read property 'bold' of undefined

### ISSUE THREAD

**Issue by dviramontes** [wlepinski/generator-meanstack#4]
Refencing : https://github.com/yeoman/generator-webapp/issues/137

Getting error while $ yo meanstack

/usr/local/share/npm/lib/node_modules/generator-meanstack/node_modules/yeoman-generator/lib/util/common.js:5
'\n   `---------´  |    ' + 'Welcome to Yeoman,'.yellow.bold + '    |' +
                                                       ^
TypeError: Cannot read property 'bold' of undefined

**Comment by dviramontes** [comment]
so far I have tried
$ npm clean cache
and
$ npm cache clean && npm uninstall -g generator-meanstack && npm install -g generator-meanstack
with not luck.

any ideas?
node v0.10.15 & 
npm 1.3.5

**Comment by wlepinski** [comment]
Hi @dviramontes. Try grab the version 0.0.4. Thanks!

**Comment by dviramontes** [comment]
Hello @wlepinski ,
no, thank you!

**Comment by dunderjeep** [comment]
thanks wlepinski - worked for me
for the lazy like me : on windows (npm install -g generator-angular)
