### ISSUE TITLE
--coffee switch

### ISSUE THREAD

**Issue by lazo99** [wlepinski/generator-meanstack#7]
When I run:

yo meanstack --coffee

the scaffold files are JS not CS

**Comment by wlepinski** [comment]
Do you think this switch should act only on frontend files?

**Comment by lazo99** [comment]
personally I would like it to be all files,everything from the Karma r test all the way through the controllers. pretty much coffee All around

**Comment by wlepinski** [comment]
Hum, I understand.
We'll need to figure out the best way to do that. Do you have any example of another generators that does the same thing?

**Comment by lazo99** [comment]
Currently

yo angular --coffee

will convert all the JS files to CS files in the app directory
